import React from 'react';
export default {
	RECEIVED_RISKS: 'RECEIVED_RISKS',
	RECEIVED_ONE_RISK: 'RECEIVED_ONE_RISK',
	RECEIVED_CHECKS: 'RECEIVED_CHECKS',
	RECEIVED_ONE_CHECK: 'RECEIVED_ONE_CHECK',
	UPDATED_ONE_CHECK: 'UPDATED_ONE_CHECK',
	RECEIVED_PATIENTS: 'RECEIVED_PATIENTS'
}